export const FETCHING_ALLNEWS_REQUEST = "FETCHING_ALLNEWS_REQUEST";
export const FETCHING_ALLNEWS_SUCCESS = "FETCHING_ALLNEWS_SUCCESS";
export const FETCHING_ALLNEWS_FAILURE = "FETCHING_ALLNEWS_FAILURE";