export const FETCHING_PROFILE_REQUEST = "FETCHING_PROFILE_REQUEST";
export const FETCHING_PROFILE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_PROFILE_FAILURE = "FETCHING_PROFILE_FAILURE";