const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
const GET_WEATHER_PENDING = 'GET_WEATHER_PENDING';
const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE';

export default {
  GET_WEATHER_SUCCESS,
  GET_WEATHER_PENDING,
  GET_WEATHER_FAILURE,
}